# Generated by Django 3.0.8 on 2020-07-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myarts', '0003_auto_20200727_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='content_type',
            field=models.CharField(blank=True, help_text='The MIMEType of the file', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='picture',
            field=models.BinaryField(blank=True, editable=True, null=True),
        ),
    ]
