# Generated by Django 3.0.8 on 2020-07-27 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Iso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Manytomany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unesco.Category')),
                ('iso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unesco.Iso')),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('justification', models.TextField()),
                ('year', models.IntegerField()),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('area_hectares', models.FloatField()),
                ('iso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unesco.Iso')),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('site', models.ManyToManyField(through='unesco.Manytomany', to='unesco.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('site', models.ManyToManyField(through='unesco.Manytomany', to='unesco.Site')),
            ],
        ),
        migrations.AddField(
            model_name='manytomany',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unesco.Region'),
        ),
        migrations.AddField(
            model_name='manytomany',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unesco.Site'),
        ),
        migrations.AddField(
            model_name='manytomany',
            name='states',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unesco.States'),
        ),
        migrations.AddField(
            model_name='category',
            name='site',
            field=models.ManyToManyField(through='unesco.Manytomany', to='unesco.Site'),
        ),
    ]
